server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_boot_21_data_jpa_application_3?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true
