server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_data_rest_redis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: weilai09290013
  data:
    rest:
      base-path: /api/v1 #指定restful的前缀
