spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_boot_security?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: weilai09290013
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false

