server:
  port: 18008
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_data_jpa?useUnicode=true&characterEncoding=utf-8
    username: root
    password: weilai
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    show-sql: true
