server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://rm-uf628q6bh4m2ss592go.mysql.rds.aliyuncs.com:3306/db_sp-esms_dev?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sp-esms
    password: rgb@2019.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /api