server:
  shutdown: graceful #　平滑关闭
  port: 0 # 0 是随机端口
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  boot:
    admin:
      client:
        url: http://localhost:9999 # The URL of the Spring Boot Admin Server to register at.
# endpoint
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        # As with Spring Boot 2 most of the endpoints aren’t exposed via http by default, we expose all of them. For production you should carefully choose which endpoints to expose.
# spring-boot-admin