spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_flowable_spring_boot?characterEncoding=UTF-8
    username: root
    password: weilai09290013
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
